version: '2'
services:
    jhipstersample-app:
        image: jhipstersample
        external_links:
            - jhipstersample-mysql:mysql
            - jhipstersample-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/jhipstersample?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    jhipstersample-mysql:
        extends:
            file: mysql.yml
            service: jhipstersample-mysql
    jhipstersample-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jhipstersample-elasticsearch
